"""empty message

Revision ID: 538ea73ef6e0
Revises: None
Create Date: 2015-03-15 20:33:10.411687

"""

# revision identifiers, used by Alembic.
revision = '538ea73ef6e0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('bin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bin')
    op.drop_table('user')
    ### end Alembic commands ###
